import type { Metadata } from "next";

import { PolicyPage } from "@/components/layout/policy-page";

export const metadata: Metadata = { title: "AI-Assistance Policy", description: "How Topicora uses AI tools while preserving human editorial responsibility.", alternates: { canonical: "/ai-assistance-policy" } };

export default function AiAssistancePolicyPage() {
  return <PolicyPage eyebrow="Responsible tools" title="AI-Assistance Policy" intro="AI can support parts of editorial work, but it cannot hold responsibility. Topicora keeps that responsibility with identifiable human editors."><h2>Permitted assistance</h2><p>Editors may use AI tools to explore an outline, identify questions for further research, check readability, propose metadata, or support repetitive production work. Any output used in publication must be reviewed and adapted by a human.</p><h2>Prohibited uses</h2><p>Topicora does not automatically publish AI-generated articles. AI output cannot serve as a factual source, fabricate a quotation or experience, imitate a living writer, conceal sponsorship, or bypass image and text permissions. Confidential reader messages, passwords, private business material, and sensitive personal data must not be placed into general-purpose AI systems.</p><h2>Verification and originality</h2><p>Claims are checked against reliable external sources, ideally primary material. Editors remain responsible for accidental plagiarism, invented references, outdated details, and unsupported certainty. Fluency is never treated as verification.</p><h2>Disclosure</h2><p>An article carries an AI-assisted disclosure when AI materially shaped its structure, drafting, visual production, analysis, or editing beyond ordinary spelling and grammar tools. The note should describe the assistance in language a reader can understand.</p><h2>Human accountability</h2><p>A human editor decides whether the article is accurate, fair, useful, and ready to publish. Readers can report concerns through the correction process regardless of which tools were used.</p></PolicyPage>;
}
