import { Archive, ExternalLink, FilePlus2, RotateCcw, Trash2 } from "lucide-react";
import Link from "next/link";

import { changeArticleStatusAction, deleteArticleAction } from "@/lib/actions/articles";
import { requireStaff } from "@/lib/auth/server";
import { getAdminArticles } from "@/lib/db/admin";
import { formatDate } from "@/lib/utils/date";

export default async function AdminArticlesPage() {
  const [articles, profile] = await Promise.all([getAdminArticles(), requireStaff("/admin/articles")]);
  return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Content library</p><h1 className="headline-md mt-2">Articles</h1></div><Link className="button-primary" href="/admin/articles/new"><FilePlus2 aria-hidden="true" size={16} /> New article</Link></div><div className="mt-8 overflow-x-auto rounded-xl border border-border bg-surface"><table className="w-full min-w-[780px] text-left text-sm"><thead className="border-b border-border bg-muted"><tr><th className="p-4">Article</th><th className="p-4">Status</th><th className="p-4">Updated</th><th className="p-4 text-right">Actions</th></tr></thead><tbody className="divide-y divide-border">{articles.map((article) => <tr key={article.id}><td className="p-4"><Link className="font-bold hover:text-accent" href={`/admin/articles/${article.id}/edit`}>{article.title}</Link><p className="mt-1 text-xs text-muted-foreground">{article.slug}{article.is_featured ? " · Featured" : ""}</p></td><td className="p-4 capitalize">{article.status}</td><td className="p-4 text-muted-foreground">{formatDate(article.updated_at)}</td><td className="p-4"><div className="flex justify-end gap-1"><Link className="button-ghost size-10 p-0" href={`/articles/${article.slug}`} target="_blank" aria-label={`Open ${article.title}`}><ExternalLink aria-hidden="true" size={16} /></Link>{article.status === "archived" ? <form action={changeArticleStatusAction.bind(null, article.id, "draft")}><button className="button-ghost size-10 p-0" type="submit" aria-label={`Restore ${article.title}`}><RotateCcw aria-hidden="true" size={16} /></button></form> : <form action={changeArticleStatusAction.bind(null, article.id, "archived")}><button className="button-ghost size-10 p-0" type="submit" aria-label={`Archive ${article.title}`}><Archive aria-hidden="true" size={16} /></button></form>}{profile.role === "admin" ? <form action={deleteArticleAction.bind(null, article.id)}><button className="button-ghost size-10 p-0 text-danger" type="submit" aria-label={`Permanently delete ${article.title}`}><Trash2 aria-hidden="true" size={16} /></button></form> : null}</div></td></tr>)}</tbody></table>{articles.length === 0 ? <p className="p-8 text-center text-muted-foreground">No articles yet. Create the first draft.</p> : null}</div></div>;
}
