import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

import {
  demoArticles,
  demoAuthor,
  demoCategories,
  demoTags,
} from "../lib/demo/articles";

const sql = (value: string | null) =>
  value === null ? "null" : `'${value.replaceAll("'", "''")}'`;

const values = (rows: string[][]) =>
  rows.map((row) => `  (${row.join(", ")})`).join(",\n");

const articleRows = demoArticles.map((article) => [
  sql(article.id),
  sql(article.authorId),
  sql(article.category.id),
  sql(article.title),
  sql(article.slug),
  sql(article.excerpt),
  sql(article.contentMarkdown),
  sql(article.coverImageUrl),
  sql(article.coverImageAlt),
  sql(article.coverImageCaption),
  sql("published"),
  sql(article.disclosure),
  sql(article.disclosureNote),
  article.isFeatured ? "true" : "false",
  sql(article.publishedAt),
  sql(article.seoTitle),
  sql(article.seoDescription),
  String(article.readingTimeMinutes),
  sql(article.updatedAt),
]);

const seed = `-- Generated by scripts/generate-seed.ts from lib/demo/articles.ts.
-- The demo author has no password and cannot authenticate. Create real staff with pnpm create-admin.

insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  confirmation_token, email_change, email_change_token_new, recovery_token
) values (
  '00000000-0000-0000-0000-000000000000',
  ${sql(demoAuthor.id)},
  'authenticated',
  'authenticated',
  'editorial-desk@topicora.local',
  null,
  now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  ${sql(JSON.stringify({ display_name: demoAuthor.displayName }))}::jsonb,
  now(), now(), '', '', '', ''
) on conflict (id) do nothing;

insert into public.profiles (id, display_name, slug, bio, role)
values (${sql(demoAuthor.id)}, ${sql(demoAuthor.displayName)}, ${sql(demoAuthor.slug)}, ${sql(demoAuthor.bio)}, 'author')
on conflict (id) do update set
  display_name = excluded.display_name,
  slug = excluded.slug,
  bio = excluded.bio;

insert into public.categories (id, name, slug, description, sort_order) values
${values(demoCategories.map((item) => [sql(item.id), sql(item.name), sql(item.slug), sql(item.description), String(item.sortOrder)]))}
on conflict (id) do update set name = excluded.name, slug = excluded.slug,
  description = excluded.description, sort_order = excluded.sort_order;

insert into public.tags (id, name, slug) values
${values(demoTags.map((item) => [sql(item.id), sql(item.name), sql(item.slug)]))}
on conflict (id) do update set name = excluded.name, slug = excluded.slug;

insert into public.articles (
  id, author_id, category_id, title, slug, excerpt, content_markdown,
  cover_image_url, cover_image_alt, cover_image_caption, status, disclosure,
  disclosure_note, is_featured, published_at, seo_title, seo_description,
  reading_time_minutes, updated_at
) values
${values(articleRows)}
on conflict (id) do update set
  author_id = excluded.author_id,
  category_id = excluded.category_id,
  title = excluded.title,
  slug = excluded.slug,
  excerpt = excluded.excerpt,
  content_markdown = excluded.content_markdown,
  cover_image_url = excluded.cover_image_url,
  cover_image_alt = excluded.cover_image_alt,
  cover_image_caption = excluded.cover_image_caption,
  status = excluded.status,
  disclosure = excluded.disclosure,
  disclosure_note = excluded.disclosure_note,
  is_featured = excluded.is_featured,
  published_at = excluded.published_at,
  seo_title = excluded.seo_title,
  seo_description = excluded.seo_description,
  reading_time_minutes = excluded.reading_time_minutes,
  updated_at = excluded.updated_at;

insert into public.article_tags (article_id, tag_id) values
${values(demoArticles.flatMap((article) => article.tags.map((tag) => [sql(article.id), sql(tag.id)])))}
on conflict do nothing;
`;

async function main() {
  const target = join(process.cwd(), "supabase", "seed.sql");
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, seed, "utf8");
  console.log(`Generated ${target}`);
  for (const article of demoArticles) {
    console.log(
      `${article.slug}: ${article.contentMarkdown.trim().split(/\s+/).length} words`,
    );
  }
}

main().catch((error: unknown) => {
  console.error(
    error instanceof Error ? error.message : "Seed generation failed.",
  );
  process.exitCode = 1;
});
