import type { Metadata } from "next";
import Link from "next/link";

import { PolicyPage } from "@/components/layout/policy-page";

export const metadata: Metadata = { title: "Terms of Use", description: "Terms governing access to and use of Topicora.", alternates: { canonical: "/terms" } };

export default function TermsPage() {
  return <PolicyPage eyebrow="Site terms" title="Terms of Use" intro="These terms describe the reasonable rules for using Topicora and its original editorial material."><h2>Using the publication</h2><p>You may read, link to, quote brief portions of, and share Topicora articles for lawful personal, educational, or commentary purposes with clear attribution. You may not reproduce substantial articles, remove attribution, impersonate Topicora, interfere with the service, or use automated access in a way that harms availability.</p><h2>Editorial information</h2><p>Articles are general information, not a substitute for professional advice. Topics evolve and material can become outdated. Read the <Link href="/disclaimer">general and financial disclaimers</Link> before making consequential decisions.</p><h2>Intellectual property</h2><p>Unless otherwise identified, Topicora’s writing, visual identity, and original graphics belong to the publication. Third-party names and marks belong to their respective owners. Linking does not imply endorsement.</p><h2>Reader submissions</h2><p>You remain responsible for information sent through the contact form. Do not submit unlawful material, passwords, confidential records, or someone else’s sensitive personal information. You grant Topicora permission to use a correction submission only as needed to investigate, update, and document the issue.</p><h2>Availability and liability</h2><p>We work to keep Topicora accurate and available but do not promise uninterrupted access or error-free content. To the extent permitted by applicable law, Topicora is not liable for indirect loss arising from reliance on the publication or temporary unavailability.</p><h2>Changes and contact</h2><p>We may update these terms when the service changes. Continued use after an update means the revised terms apply. Questions can be sent through the <Link href="/contact">contact page</Link>.</p></PolicyPage>;
}
